homework/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from .views import home, book, index, bio

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$|^home/', home, name='home-view'),
    path('index/', index, name='index-view'),
    path('bio/<str:user_name>/', bio, name='bio'),
    path('book/<str:title>/', book, name='book'),
    path('lesson_1/', include('lesson_1.urls')),
    path('lesson_2/', include('lesson_2.urls')),
    path('lesson_3/', include('lesson_3.urls')),
    path('lesson_4/', include('lesson_4.urls')),
    path('lesson_5/', include('lesson_5.urls')),
    path('lesson_7/', include('lesson_7.urls')),

]

lesson_3/urls.py
from django.urls import path
from .views import (task_1, task_2, luk, lea, khan,
                    task_3, task_3_file, task_5, task_6,
                    task_7)

app_name = 'lesson_3'

urlpatterns = [
    path('task_1/', task_1, name='task_3_1'),
    path('task_2/', task_2, name='task_2'),
    path('task_2/luk/', luk, name='luk'),
    path('task_2/lea/', lea, name='lea'),
    path('task_2/khan/', khan, name='khan'),
    path('task_3/', task_3, name='task_3'),
    path('task_3/file/', task_3_file, name='file'),
    path('task_5/', task_5, name='task_5'),
    path('task_6/', task_6, name='task_6'),
    path('task_7/polls/', task_7, name='task_7'),
    path('task_7/polls/<int:question_id>/', task_7, name='question_detail')
]

lesson_3/views.py
from django.shortcuts import render
from django.http import HttpResponse


def task_1(request):
    lets_do_it = [{'priority': 100, 'task': 'Скласти перелік справ'},
                  {'priority': 150, 'task': 'Вивчати Django'},
                  {'priority': 1, 'task': 'Подумати про сенс життя'}]
    return HttpResponse(f'<h1>Plan</h1><p>{str(lets_do_it)}</p>')


def task_2(request):
    return render(request, 'lesson_3/task_2.html')


def luk(request):
    return HttpResponse("""
                        <h1>Сторінка Люка:</h1>
                        <p>Люк Скайуокер — один із головних персонажів всесвіту «Зоряних війн», джедай, син сенатора 
                        з Набу Падме Амідали Наберрі та лицаря-джеда Енакіна Скайуокера.</p>
                        """)


def lea(request):
    return HttpResponse("""
                        <h1>Сторінка Леї:</h1>
                        <p>Лея Органа — дочка лицаря-джеда Енакіна Скайуокера та сенатора Падме Амідали Наберрі.</p>
                        """)


def khan(request):
    return HttpResponse("""
                        <h1>Сторінка Хана:</h1>
                        <p>Хан. Соло — пілот космічного корабля «Тисячолітній сокіл», його бортмеханіком та другим 
                        пілотом є вуки на ім'я Чубакка.</p>
                        """)


def task_3(request):
    return render(request, 'lesson_3/task_3.html')


def task_3_file(request):
    with open('lesson_3/answer.txt', 'rb') as file:
        data = file.read()
    content = data
    response = HttpResponse(content, status=227, content_type='application/msword')
    response['Content-Disposition'] = 'attachment; filename="answer.doc"'
    return response


def task_5(request):
    lets_do_it = [{'priority': 100, 'task': 'Скласти перелік справ'},
                  {'priority': 150, 'task': 'Вивчати Django'},
                  {'priority': 1, 'task': 'Подумати про сенс життя'}]
    context = {"do_list": lets_do_it}
    return render(request, 'lesson_3/task_5.html', context)


def task_6(request):
    persons = [
        {'name': 'Шаддам IV', 'surname': 'Корріно'},
        {'name': 'Стать', 'surname': 'Атрейдес'},
        {'name': 'Франклін', 'surname': 'Герберт'}]
    context = {'persons': persons}
    return render(request, 'lesson_3/task_6.html', context)


def task_7(request, question_id=None):
    latest_question_list = [{'id': 1, 'question_text': 'У чому сенс життя?'},
                            {'id': 2, 'question_text': 'Що первинне: дух чи матерія?'},
                            {'id': 3, 'question_text': 'Чи існує свобода волі?'}]
    # latest_question_list = []
    if question_id:
        for question in latest_question_list:
            if question['id'] == question_id:
                context = {'question': question}
                return render(request, 'lesson_3/detail.html', context)
        else:
            return HttpResponse(f'Питання під таким номером {question_id} немає в списку')
    context = {'latest_question_list': latest_question_list}
    return render(request, 'lesson_3/task_7.html', context)

templates/lesson_3/detail.html
<!DOCTYPE HTML>

<html>
<head>
    <meta charset="UTF-8">
    <title>Завдання 7!</title>
</head>
<body>
<h1>Сторінка запитання {{ question.id }}</h1>
{{ question.question_text }}
</body>

</html>

templates/lesson_3/main.html
<!DOCTYPE HTML>

<html>
<head>
    <meta charset="UTF-8">
    <title>Зоряні війни</title>
</head>
<body>
<h1>Ласкаво просимо до всесвіту зоряних воєн!</h1>
<p>Оберіть сторінку:</p>
<ul>
    <li><a href="{% url 'lesson_3:luk' %}">Люк</a></li>
    <li><a href="{% url 'lesson_3:lea' %}">Лея</a></li>
    <li><a href="{% url 'lesson_3:khan' %}">Хан</a></li>
</ul>
</body>

</html>

templates/lesson_3/task_2.html
<!DOCTYPE HTML>

<html>
<head>
    <meta charset="UTF-8">
    <title>Зоряні війни</title>
</head>
<body>
<h1>Ласкаво просимо до всесвіту зоряних воєн!</h1>
<p>Оберіть сторінку:</p>
<ul>
    <li><a href="{% url 'lesson_3:luk' %}">Люк</a></li>
    <li><a href="{% url 'lesson_3:lea' %}">Лея</a></li>
    <li><a href="{% url 'lesson_3:khan' %}">Хан</a></li>
</ul>
</body>

</html>

templates/lesson_3/task_3.html
<html>
<head>
    <meta charset="UTF-8">
    <title>Завдання 3!</title>
</head>
<body>
<h1>Завдання 3</h1>
<a href="{% url 'lesson_3:file' %}">Отримати відповідь</a>
</body>

</html>

templates/lesson_3/task_5.html
<!DOCTYPE HTML>

<html>
<head>
    <meta charset="UTF-8">
    <title>Завдання 5!</title>
</head>
<body>
<h1>Давай зробимо це!</h1>
{% for do in do_list|dictsortreversed:"priority" %}
<p>{{ do }}</p>
{% endfor %}
</body>

</html>

templates/lesson_3/task_6.html
<!DOCTYPE HTML>

<html>
<head>
    <meta charset="UTF-8">
    <title>Завдання 6!</title>
</head>
<body>
<h1>Список осіб</h1>
<ol>
{% for person in persons %}
<li>{{ person.name }} {{ person.surname }}</li>
{% endfor %}
</ol>
</body>

</html>

templates/lesson_3/task_7.html
<!DOCTYPE HTML>

<html>
<head>
    <meta charset="UTF-8">
    <title>Завдання 7!</title>
</head>
<body>
<h1>Список запитань</h1>
{% if latest_question_list %}
<ul>
{% for question in latest_question_list %}
    <li><a href="{% url 'lesson_3:question_detail' question.id %}">{{ question.question_text }}</a></li>
{% endfor %}
</ul>
{% else %}
Список завдань порожній
{% endif %}


</body>

</html>